on:
  push:
    branches: ["*"]

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          token: ${{ secrets.PYCOSIM_UPLOAD }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          include-component-in-tag: true
      - name: Print the output
        run: echo "The output was $ALLOUTPUT"
        env:
          ALLOUTPUT: ${{ toJSON(steps.release.outputs) }}
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - name: Set up Python
        uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          python-version: "3.12"
      - name: Install pypa/build
        if: ${{ steps.release.outputs.releases_created }}
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build feems
        if: ${{ steps.release.outputs.feems--release_created }}
        run: python3 -m build
        working-directory: feems
      - name: Publish feems to PyPI
        if: ${{ steps.release.outputs.feems--release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: feems/dist
      - name: Build MachSysS
        if: ${{ steps.release.outputs.machinery-system-structure--release_created }}
        run: python3 -m build
        working-directory: machinery-system-structure
      - name: Publish ship_model_lib to PyPI
        if: ${{ steps.release.outputs.machinery-system-structure--release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: machinery-system-structure/dist
      - name: Build RunFEEMSSim
        if: ${{ steps.release.outputs.RunFEEMSSim--release_created }}
        run: python3 -m build
        working-directory: RunFEEMSSim
      - name: Publish RunFEEMSSim to PyPI
        if: ${{ steps.release.outputs.RunFEEMSSim--release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: RunFEEMSSim/dist
